### ISSUE TITLE
Add support for uploading ProGuard map files

### ISSUE THREAD

**Issue by JesperSjoquist** [microsoft/google-play-vsts-extension#14]
Add ability to upload ProGuard obfuscation map files, what google in the developer console calls "deobfuscation files".

**Comment by JesperSjoquist** [comment]
Currently not supported by the API, but an issue has been created here: https://code.google.com/p/android/issues/detail?id=203432

**Comment by lostintangent** [comment]
@JesperSjoquist Totally agreed that this would be useful! It would be a trivial enhancement on our end, but as you mentioned, I'm not sure when we could expect to be able to do this, since we'd rely on Google Play changes.

I noticed that you left a comment on the VSTS marketplace about needing this feature in order to adopt this extension. Is that still the case? I'd love to unblock you to use it if we can.

**Comment by JesperSjoquist** [comment]
@lostintangent Thanks for the quick response and a great extension!

As an interim solution I have modified our build process to upload a production version to both Google Play alpha and HockeyApp, where HockeyApp will save the mapping files for us.

**Comment by JesperSjoquist** [comment]
Support for uploading mapping files has now been added the the Google API:
https://code.google.com/p/android/issues/detail?id=203432

**Comment by esh0** [comment]
Is there any possibility to investigate again the possibility of adding the proguard file upload?

**Comment by lassem** [comment]
Another year; time for a ping.

**Comment by madhurig** [comment]
This is not on our backlog for Q1 of 2019 due to other priorities. If we get a community contribution, we will be able to do the release but are unable to fund it in this quarter otherwise.
