### ISSUE TITLE
Change log is hard coded to US English language

### ISSUE THREAD

**Issue by simon-biber** [Microsoft/google-play-vsts-extension#27]
We get an error from Google Play saying "Tried to set recent changes text for APK version 3 for language en-US. Language is not associated with the app."

I suggest making this language configurable instead of hard coding it to "en-US" in Tasks/google-play-release/GooglePlay.js line 248.

`return addChangelog("en-US", changelogFile, apkVersionCode);
`

**Comment by madhurig** [comment]
@simon-biber: Thanks for reporting the issue, we will add it in the next update. 

-Madhuri

**Comment by ryuyu** [comment]
It looks like we only hit this path if a specific changelog file is indicated from the UI.

There are two possible corrections here for us.
1. We can add another UI element to specify the language of the indicated changelog
2. We remove the ability to specify changelog and require that the any changelogs fit the new metadata format to be picked up and remove that code path entirely.

@madhurig I leave it up to you to decide which is correct.

**Comment by CaLxCyMru** [comment]
Hey @madhurig - Is there any update on the progress/work around for this?

**Comment by DavidStaheli** [comment]
Hi @CaLxCyMru, we haven't decided on the approach yet, but we expect to have it implemented this month (April 2017).

Thank you for the 2 possible ways to address this.  Personally, I'm in favor of adding the "Changelog Language" field because removing the ability to specify a changelog could break existing use of the extension.  But then the next _major_ version of this extension could remove the ability to specify a changelog and rely on the new metadata format.  The framework requires users to opt into new _major_ versions so that compatibility isn't broken.

Thanks again for your suggestions...

**Comment by AlexRukhlin** [comment]
Implemented with the commit [cc19a46d9](https://github.com/Microsoft/google-play-vsts-extension/commit/cc19a46d90bc17b632674d7484522d4a65d80585)
