### ISSUE TITLE
Google play bundle release task does not validate bundle path input

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/google-play-vsts-extension#294]
Looks like Google play bundle release task does not validate empty bundle path input - we need to check it.

**Comment by DaniilShmelev** [comment]
AZDO automatically fills empty inputs of type `filePath` with `$(Build.SourcesDir)`. Furthermore, the file existence check is done via `tl.checkPath`. This method does not throw if a given path is a folder.
So, if we provide an empty input in the pipeline YAML, it will be filled with `/home/vsts/work/1/s` in the task code. Then this path is checked through `tl.checkPath`, and since this folder exists, the task thinks it has found an existing bundle file.

**Comment by DaniilShmelev** [comment]
Not going to fix since the issue is not critical. The error will still appear when we try to upload the folder via googlapis
