### ISSUE TITLE
Screenshot images are getting duplicated

### ISSUE THREAD

**Issue by epopov** [Microsoft/google-play-vsts-extension#34]
Hi. Images in the store are getting duplicated after two metadata updates. According to the documentation, the process should remove all existing screenshot and replace them with new images from the metadata folder.

**Comment by ryuyu** [comment]
Do you have metadata in multiple languages?

Can you attach a log of a build that generate multiple metadata entries?
If you run your VSTS build with the variable system.debug set to true, the task should output a lot of debugging information for us to take a look at what's going on.

**Comment by JaPawel** [comment]
I think current screenshots are not removed before new ones are added. In my case I have 5 files in phoneScreenshots directory. When doing next release I get this error: "This app has more than 8 screenshots".

Here is log from my agent (if you need I may try to generate one with system.debug set to true):
> ===
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 1.112.0
Author       : Microsoft Corporation
Help         : 
===
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx exists true
Authenticated with Google Play and getting new edit 
Uploading APK file /Users/xxxxx/agent/_work/r1/a/Android/drop/app-publish-release.apk...
Updating track information...
Attempting to attach metadata to release...
Attempting to upload metadata in /Users/xxxxx/agent/_work/r1/a/Android/drop/metadata/en-US for language code en-US
Appending changelog /Users/xxxxx/agent/_work/r1/a/Android/drop/metadata/en-US/changelogs/21001.txt
Found image for type featureGraphic at /Users/xxxxx/agent/_work/r1/a/Android/drop/metadata/en-US/images/featureGraphic.png
Found image for type icon at /Users/xxxxx/agent/_work/r1/a/Android/drop/metadata/en-US/images/icon.png
Image for promoGraphic was not found. Skipping...
Image for tvBanner was not found. Skipping...
Image directory for sevenInchScreenshots was not found. Skipping...
Image directory for tenInchScreenshots was not found. Skipping...
Image directory for tvScreenshots was not found. Skipping...
Image directory for wearScreenshots was not found. Skipping...
{ [Error: This app has more than 8 screenshots for language en_US.]
  cause: { [Error: This app has more than 8 screenshots for language en_US.] code: 403, errors: [ [Object] ] },
  isOperational: true,
  code: 403,
  errors: 
   [ { domain: 'androidpublisher',
       reason: 'tooManyScreenshots',
       message: 'This app has more than 8 screenshots for language en_US.' } ] }
##[error]Failed to publish APKs.
##[section]Finishing: Release to alpha

When doing with fastlane supply, everything is ok - they at first remove current screenshots and then adding new ones from metadata directory [here is supply code](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L98)

My current workaround is to manually, before committing code to repo (so before build and then release starts), remove few screenshots in Google Play Dev Console (I need to leave two to be able to save), and then after release remove those two screenshots I left (because the new ones are appended and duplicates those left).

**Comment by AlexRukhlin** [comment]
Implemented with the commit [aac3b95](https://github.com/Microsoft/google-play-vsts-extension/commit/aac3b95fc7975af926b3263664b7db4588aae59f)
