### ISSUE TITLE
Error multiAPKshadowedActiveAPK

### ISSUE THREAD

**Issue by wimhaesen** [Microsoft/google-play-vsts-extension#69]
Hi,

I got this error:

Authenticated with Google Play and getting new edit 
Updating track information...
 ##[error]Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"multiApkShadowedActiveApk","message":"Version 10001 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"multiApkShadowedActiveApk","message":"Version 10001 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."}]}

I want to publish to a beta track with new version code 10004, active version in beta is 10003.
There is no version 10001 anymore?

There was one in the past in alfa, but alfa does not exist anymore as it is replaced by beta.

Please help.

Thanks.

**Comment by madhurig** [comment]
The error is valid i.e. if a higher versionCode is uploaded to Beta, it supersedes the Alpha, so the lower versionCode Alpha APK will not be downloadable. Did you upload 10003 to Beta manually via the Google Developer Console? In that case, you should see something like this in the Google Developer console in App Releases:
<img width="742" alt="gp" src="https://user-images.githubusercontent.com/3269636/27701063-b1f0bfe4-5ccd-11e7-88db-87415165d52b.png">

You can try deactivating the older version in Alpha to upload new version to Beta track. The extension does not have support to deactivate older superseded versions in other tracks. Another option with the extension is to upload higher version to Alpha track and promote it to Beta track.

This issue is same as https://github.com/Microsoft/google-play-vsts-extension/issues/44 

Thanks,
Madhuri
